"""Token: add expire_at column

Revision ID: 22349abb947f
Revises: 5e15975b8c5b
Create Date: 2025-05-29 00:13:33.150720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22349abb947f'
down_revision: Union[str, None] = '5e15975b8c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('expire_at', sa.Integer(), nullable=False))
    op.drop_index('ix_token_created_at', table_name='token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_token_created_at', 'token', ['created_at'], unique=False)
    op.drop_column('token', 'expire_at')
    # ### end Alembic commands ###
